export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const CHANGE_USERS = 'CHANGE_USERS';
export const REPLACE_USERS = 'REPLACE_USERS';
export const CHANGE_LOADING = 'CHANGE_LOADING';
export const CHANGE_ACTIVE_USER = 'CHANGE_ACTIVE_USER';
